version: '3'
services:
  mqtt-broker:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"
      - "8080:8080"

# TODO AD
#  backend:
#    image: your-aspnet-image
#    depends_on:
#      - mqtt-broker
#      - mongodb
#    networks:
#      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/usr/src/app