version: '3'
services:
  hivemq:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"
      - "8080:8080"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    image: si_frontend
    build: ./Frontend      
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/usr/src/app

  backend:
    image: si_backend
    build: ./Backend
    ports:
      - "32769:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hivemq
      - mongodb